"""message likes and thread reads

Revision ID: 1f32ea198a38
Revises: bab0de8bfc18
Create Date: 2026-07-11 17:39:29.174779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f32ea198a38'
down_revision: Union[str, None] = 'bab0de8bfc18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thread_reads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id', 'user_id', name='uq_thread_read')
    )
    op.create_index(op.f('ix_thread_reads_thread_id'), 'thread_reads', ['thread_id'], unique=False)
    op.create_index(op.f('ix_thread_reads_user_id'), 'thread_reads', ['user_id'], unique=False)
    op.create_table('message_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['thread_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', name='uq_message_like')
    )
    op.create_index(op.f('ix_message_likes_message_id'), 'message_likes', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_likes_message_id'), table_name='message_likes')
    op.drop_table('message_likes')
    op.drop_index(op.f('ix_thread_reads_user_id'), table_name='thread_reads')
    op.drop_index(op.f('ix_thread_reads_thread_id'), table_name='thread_reads')
    op.drop_table('thread_reads')
    # ### end Alembic commands ###
