"""disciple.ready_for_pranama

Revision ID: 33d5fd90e6ad
Revises: 941f24d7f1a4
Create Date: 2026-07-11 15:00:26.591994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33d5fd90e6ad'
down_revision: Union[str, None] = '941f24d7f1a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disciples', sa.Column('ready_for_pranama', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disciples', 'ready_for_pranama')
    # ### end Alembic commands ###
