"""countries, regions, disciple.region

Revision ID: 685369be995b
Revises: b93e62771140
Create Date: 2026-07-11 14:17:29.173027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '685369be995b'
down_revision: Union[str, None] = 'b93e62771140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_name'), 'countries', ['name'], unique=True)
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regions_name'), 'regions', ['name'], unique=True)
    op.add_column('disciples', sa.Column('region', sa.String(length=160), nullable=True))
    op.create_index(op.f('ix_disciples_region'), 'disciples', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disciples_region'), table_name='disciples')
    op.drop_column('disciples', 'region')
    op.drop_index(op.f('ix_regions_name'), table_name='regions')
    op.drop_table('regions')
    op.drop_index(op.f('ix_countries_name'), table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
