"""mentor as disciple flag + role permissions

Revision ID: 934a68399b8e
Revises: cd188af03542
Create Date: 2026-07-11 18:21:03.936804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '934a68399b8e'
down_revision: Union[str, None] = 'cd188af03542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('guru', 'secretary', 'curator', 'student', name='role', native_enum=False), nullable=False),
    sa.Column('section', sa.String(length=40), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role', 'section', name='uq_role_section')
    )
    op.create_index(op.f('ix_role_permissions_role'), 'role_permissions', ['role'], unique=False)
    op.add_column('disciples', sa.Column('is_mentor', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.create_index(op.f('ix_disciples_is_mentor'), 'disciples', ['is_mentor'], unique=False)
    op.drop_constraint('disciples_mentor_id_fkey', 'disciples', type_='foreignkey')
    op.create_foreign_key(None, 'disciples', 'disciples', ['mentor_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'disciples', type_='foreignkey')
    op.create_foreign_key('disciples_mentor_id_fkey', 'disciples', 'users', ['mentor_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_disciples_is_mentor'), table_name='disciples')
    op.drop_column('disciples', 'is_mentor')
    op.drop_index(op.f('ix_role_permissions_role'), table_name='role_permissions')
    op.drop_table('role_permissions')
    # ### end Alembic commands ###
