"""disciple.pranama_date

Revision ID: 941f24d7f1a4
Revises: 685369be995b
Create Date: 2026-07-11 14:51:08.412896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '941f24d7f1a4'
down_revision: Union[str, None] = '685369be995b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disciples', sa.Column('pranama_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disciples', 'pranama_date')
    # ### end Alembic commands ###
