"""threads and messages

Revision ID: bab0de8bfc18
Revises: 33d5fd90e6ad
Create Date: 2026-07-11 17:16:27.372389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bab0de8bfc18'
down_revision: Union[str, None] = '33d5fd90e6ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('question', 'report', name='threadkind', native_enum=False), nullable=False),
    sa.Column('disciple_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('period', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['disciple_id'], ['disciples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threads_disciple_id'), 'threads', ['disciple_id'], unique=False)
    op.create_index(op.f('ix_threads_kind'), 'threads', ['kind'], unique=False)
    op.create_table('thread_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thread_messages_thread_id'), 'thread_messages', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thread_messages_thread_id'), table_name='thread_messages')
    op.drop_table('thread_messages')
    op.drop_index(op.f('ix_threads_kind'), table_name='threads')
    op.drop_index(op.f('ix_threads_disciple_id'), table_name='threads')
    op.drop_table('threads')
    # ### end Alembic commands ###
