"""initial schema

Revision ID: e06f39d6497a
Revises: 
Create Date: 2026-07-11 10:38:51.797325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e06f39d6497a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('president_name', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('guru', 'secretary', 'curator', 'student', name='role', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('disciple_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['disciple_id'], ['disciples.id'], name='fk_users_disciple_id', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('disciples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spiritual_name', sa.String(length=255), nullable=True),
    sa.Column('material_name', sa.String(length=255), nullable=False),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('messenger', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('temple_id', sa.Integer(), nullable=True),
    sa.Column('marital_status', sa.Enum('single', 'married', 'brahmachari', 'sannyasi', 'widowed', 'other', name='maritalstatus', native_enum=False), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('initiation_status', sa.Enum('aspirant', 'recommended', 'harinama', 'brahman', name='initiationstatus', native_enum=False), nullable=False),
    sa.Column('harinama_date', sa.Date(), nullable=True),
    sa.Column('harinama_name', sa.String(length=255), nullable=True),
    sa.Column('brahman_date', sa.Date(), nullable=True),
    sa.Column('seva', sa.Text(), nullable=True),
    sa.Column('current_activity', sa.Text(), nullable=True),
    sa.Column('mentor_id', sa.Integer(), nullable=True),
    sa.Column('recommended_by', sa.String(length=255), nullable=True),
    sa.Column('application_date', sa.Date(), nullable=True),
    sa.Column('ready_for_initiation', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disciples_country'), 'disciples', ['country'], unique=False)
    op.create_index(op.f('ix_disciples_initiation_status'), 'disciples', ['initiation_status'], unique=False)
    op.create_index(op.f('ix_disciples_material_name'), 'disciples', ['material_name'], unique=False)
    op.create_index(op.f('ix_disciples_mentor_id'), 'disciples', ['mentor_id'], unique=False)
    op.create_index(op.f('ix_disciples_spiritual_name'), 'disciples', ['spiritual_name'], unique=False)
    op.create_table('checklist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disciple_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('target', sa.Enum('aspirant', 'recommended', 'harinama', 'brahman', name='initiationstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['disciple_id'], ['disciples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_items_disciple_id'), 'checklist_items', ['disciple_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checklist_items_disciple_id'), table_name='checklist_items')
    op.drop_table('checklist_items')
    op.drop_index(op.f('ix_disciples_spiritual_name'), table_name='disciples')
    op.drop_index(op.f('ix_disciples_mentor_id'), table_name='disciples')
    op.drop_index(op.f('ix_disciples_material_name'), table_name='disciples')
    op.drop_index(op.f('ix_disciples_initiation_status'), table_name='disciples')
    op.drop_index(op.f('ix_disciples_country'), table_name='disciples')
    op.drop_table('disciples')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('temples')
    # ### end Alembic commands ###
